apiVersion: v1
kind: Service
metadata:
  name: connect
  namespace: nvt-cnt
  labels:
    app: connect
spec:
  selector:
    app: connect
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP
